# Generated by Django 6.0.3 on 2026-03-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0005_add_niveau_evaluation_field'),
        ('audit', '0003_critere_formulaire_alter_listeaudit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textref',
            name='text_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_refs', to='Organisation.processusdoc'),
        ),
    ]
