# Generated by Django 5.2.9 on 2026-02-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norme', models.CharField(max_length=255)),
                ('text_ref', models.FileField(blank=True, null=True, upload_to='text_refs/')),
            ],
        ),
    ]
