# Generated by Django 5.2.11 on 2026-02-23 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0002_processusdoc'),
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreuveAttendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeCotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypePreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='ChapitreNorme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('text_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.textref')),
            ],
        ),
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chapitre_norme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.chapitrenorme')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaireAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('processus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organisation.processus')),
                ('section', models.ManyToManyField(related_name='formulaire_audit_section', to='Organisation.section')),
                ('type_equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Organisation.typeequipement')),
            ],
        ),
        migrations.CreateModel(
            name='ListeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('number_audit', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('affectation', models.ManyToManyField(related_name='liste_audit_affectation', to=settings.AUTH_USER_MODEL)),
                ('formulaire_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.formulaireaudit')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organisation.section')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_audit', models.PositiveIntegerField()),
                ('users', models.CharField(max_length=50)),
                ('date_audit', models.DateTimeField(auto_now_add=True)),
                ('score_audit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sujet', models.CharField(max_length=50)),
                ('niveau_attendu', models.JSONField(blank=True, default=list, null=True)),
                ('reference_gamme', models.CharField(blank=True, max_length=50, null=True)),
                ('processus', models.CharField(blank=True, max_length=50, null=True)),
                ('point_fort', models.TextField(blank=True, null=True)),
                ('point_sensible', models.TextField(blank=True, null=True)),
                ('risque', models.TextField(blank=True, null=True)),
                ('opportunite', models.TextField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('en_cours', models.BooleanField(default=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.listeaudit')),
                ('audites', models.ManyToManyField(blank=True, related_name='audites', to=settings.AUTH_USER_MODEL)),
                ('auditeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditeur_resultat', to=settings.AUTH_USER_MODEL)),
                ('co_auditeur', models.ManyToManyField(blank=True, related_name='auditeur', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Organisation.site')),
            ],
        ),
        migrations.CreateModel(
            name='DetailResultatAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critere', models.CharField(max_length=50)),
                ('norme', models.CharField(blank=True, max_length=50, null=True)),
                ('sous_critere', models.CharField(max_length=255)),
                ('chapitre_norme', models.CharField(blank=True, max_length=50, null=True)),
                ('text_ref_url', models.CharField(blank=True, max_length=255, null=True)),
                ('element_preuve', models.TextField(blank=True, null=True)),
                ('justificatif', models.ImageField(blank=True, null=True, upload_to='evidence/')),
                ('justificatif_bis', models.ImageField(blank=True, null=True, upload_to='evidence/')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('cotation_option', models.JSONField(blank=True, default=list, null=True)),
                ('cotation', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('value', models.FloatField(default=0)),
                ('value_max', models.FloatField(default=0)),
                ('resultat_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.resultataudit')),
            ],
        ),
        migrations.CreateModel(
            name='SousCritere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.critere')),
                ('preuve_attendu', models.ManyToManyField(related_name='preuve_attendu_sous_critere', to='audit.preuveattendu')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaireSousCritere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.formulaireaudit')),
                ('sous_critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.souscritere')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='formulaireaudit',
            name='liste_sous_criteres',
            field=models.ManyToManyField(related_name='liste_sous_critere', through='audit.FormulaireSousCritere', to='audit.souscritere'),
        ),
        migrations.CreateModel(
            name='TypeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('section', models.ManyToManyField(blank=True, related_name='type_audit_section', to='Organisation.section')),
            ],
        ),
        migrations.CreateModel(
            name='SousCritereTypeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('obligatoire', 'Obligatoire'), ('optionnel', 'Optionnel')], default='optionnel', max_length=20)),
                ('sous_critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.souscritere')),
                ('type_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.typeaudit')),
            ],
            options={
                'unique_together': {('sous_critere', 'type_audit')},
            },
        ),
        migrations.AddField(
            model_name='souscritere',
            name='type_audit',
            field=models.ManyToManyField(blank=True, through='audit.SousCritereTypeAudit', to='audit.typeaudit'),
        ),
        migrations.AddField(
            model_name='formulaireaudit',
            name='type_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.typeaudit'),
        ),
        migrations.AddField(
            model_name='souscritere',
            name='type_cotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.typecotation'),
        ),
        migrations.CreateModel(
            name='Cotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('content', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
                ('type_cotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.typecotation')),
            ],
        ),
        migrations.AddField(
            model_name='preuveattendu',
            name='type_preuve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.typepreuve'),
        ),
    ]
