# Generated by Django 6.0.3 on 2026-04-05 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_listeaudit_site_alter_detailresultataudit_value_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeaudit',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
