# Generated by Django 6.0.3 on 2026-05-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_preuveattendu_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preuveattendu',
            name='code',
            field=models.CharField(blank=True, choices=[('C', 'Conforme'), ('PC', 'Partiellement Conforme')], max_length=2, null=True, verbose_name='Code de preuve'),
        ),
    ]
