# Generated by Django 6.0.3 on 2026-05-10 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0013_alter_preuveattendu_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeaudit',
            name='type_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.typeaudit'),
        ),
    ]
