# Generated by Django 6.0.3 on 2026-05-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0015_alter_formulairesouscritere_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='audit.detailresultataudit')),
            ],
        ),
    ]
