# Generated by Django 6.0.3 on 2026-05-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0017_alter_formulaireaudit_type_equipement'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultataudit',
            name='dummy_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
