# Generated by Django 6.0.3 on 2026-05-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0018_resultataudit_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultataudit',
            name='dummy_field',
        ),
    ]
