# Generated by Django 6.0.3 on 2026-05-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0010_alter_equipement_type_equipement'),
        ('audit', '0022_listeaudit_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaireaudit',
            name='type_equipement',
        ),
        migrations.AddField(
            model_name='formulaireaudit',
            name='type_equipement',
            field=models.ManyToManyField(blank=True, related_name='formulaire_audit_type_equipement', to='Organisation.typeequipement'),
        ),
    ]
