# Generated by Django 6.0.6 on 2026-06-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0023_remove_formulaireaudit_type_equipement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeaudit',
            name='desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resultataudit',
            name='sujet',
            field=models.CharField(max_length=255),
        ),
    ]
