# Generated by Django 5.2.9 on 2026-02-22 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauAttendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('niveau_evaluation', models.JSONField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organisation.section')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('commentaire', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organisation.site')),
                ('type_equipement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organisation.typeequipement')),
            ],
        ),
    ]
