# Generated by Django 5.2.11 on 2026-02-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessusDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.FileField(blank=True, null=True, upload_to='processus_docs/')),
                ('document_processus', models.ManyToManyField(related_name='ProcessDoc', to='Organisation.processus')),
            ],
        ),
    ]
