# Generated by Django 6.0.3 on 2026-03-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0006_remove_site_niveau_evaluation_alter_site_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niveauattendu',
            name='name',
        ),
        migrations.RemoveField(
            model_name='niveauattendu',
            name='pourcentage',
        ),
        migrations.AddField(
            model_name='niveauattendu',
            name='valeur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='niveauattendu',
            name='commentaire',
            field=models.TextField(default=''),
        ),
    ]
