# Generated by Django 6.0.3 on 2026-04-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0008_alter_niveauattendu_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organisation.site'),
        ),
    ]
