# Generated by Django 6.0.3 on 2026-03-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0007_remove_niveauattendu_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveauattendu',
            name='commentaire',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='niveauattendu',
            name='valeur',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
