# Generated by Django 6.0.3 on 2026-05-13 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0009_alter_equipement_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='type_equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organisation.typeequipement'),
        ),
    ]
