# Generated by Django 6.0.3 on 2026-03-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0005_add_niveau_evaluation_field'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaireaudit',
            name='liste_sous_criteres',
            field=models.ManyToManyField(blank=True, related_name='liste_sous_critere', through='audit.FormulaireSousCritere', to='audit.souscritere'),
        ),
        migrations.AlterField(
            model_name='formulaireaudit',
            name='section',
            field=models.ManyToManyField(blank=True, related_name='formulaire_audit_section', to='Organisation.section'),
        ),
    ]
