# Generated by Django 6.0.3 on 2026-03-22 07:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_formulaireaudit_liste_sous_criteres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='critere',
            name='formulaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='audit.formulaireaudit'),
        ),
        migrations.AlterField(
            model_name='listeaudit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='listeaudit',
            name='number_audit',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
