# Generated by Django 6.0.3 on 2026-05-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_listeaudit_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeaudit',
            name='participants_externes',
            field=models.TextField(blank=True, null=True, verbose_name='Participants Externes'),
        ),
    ]
