# Generated by Django 6.0.3 on 2026-05-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0014_listeaudit_type_audit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formulairesouscritere',
            unique_together={('formulaire', 'sous_critere')},
        ),
    ]
