# Generated by Django 6.0.3 on 2026-03-31 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0008_alter_niveauattendu_commentaire_and_more'),
        ('audit', '0004_alter_textref_text_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeaudit',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organisation.site'),
        ),
        migrations.AlterField(
            model_name='detailresultataudit',
            name='value_max',
            field=models.FloatField(default=5),
        ),
    ]
