# Generated by Django 6.0.3 on 2026-04-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_typeaudit_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeaudit',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
