# Generated by Django 6.0.3 on 2026-04-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0009_alter_equipement_site'),
        ('audit', '0007_alter_typeaudit_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultataudit',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organisation.site'),
        ),
    ]
