# Generated by Django 6.0.3 on 2026-04-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_alter_resultataudit_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='critere',
            name='type_audit',
            field=models.ManyToManyField(blank=True, related_name='criteres', to='audit.typeaudit'),
        ),
        migrations.AlterField(
            model_name='detailresultataudit',
            name='value_max',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='typeaudit',
            name='name',
            field=models.CharField(choices=[('Audit équipement', 'Audit équipement'), ('Audit interne', 'Audit interne'), ('Audit de poste', 'Audit de poste'), ('Audit de Site', 'Audit de Site')], max_length=50),
        ),
    ]
