# Generated by Django 6.0.3 on 2026-04-21 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_critere_type_audit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listeaudit',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='liste_audit_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
